import { FontInfo } from '../types/game';

export const NOONNU_FONTS: FontInfo[] = [
  {
    id: 'pretendard',
    name: '프리텐다드',
    family: 'Pretendard-Regular',
    css: "@font-face { font-family: 'Pretendard-Regular'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/pretendard@1.0/Pretendard-Thin.woff2') format('woff2'); font-weight: 400; font-style: normal; }",
  },
  {
    id: 'paperlogy',
    name: '페이퍼로지',
    family: 'Paperlogy-Bold',
    css: "@font-face { font-family: 'Paperlogy-Bold'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2408-3@1.0/Paperlogy-1Thin.woff2') format('woff2'); font-weight: 700; font-style: normal; }",
  },
  {
    id: 'gmarket-sans',
    name: 'G마켓 산스',
    family: 'GmarketSansMedium',
    css: "@font-face { font-family: 'GmarketSansMedium'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/GmarketSansMedium.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'memoment-kukkuk',
    name: '메모먼트 꾹꾹체',
    family: 'MemomentKukkuk',
    css: "@font-face { font-family: 'MemomentKukkuk'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2508-2@1.0/memomentKkukKkuk.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'jalnan',
    name: '여기어때 잘난체',
    family: 'Jalnan',
    css: "@font-face { font-family: 'Jalnan'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.2/JalnanOTF00.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 's-core-dream',
    name: '에스코어드림',
    family: 'S-CoreDream-3Light',
    css: "@font-face { font-family: 'S-CoreDream-3Light'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-3Light.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'ongle-parkdahyun',
    name: '온글잎 박다현체',
    family: 'Ongle_ParkDaHyun',
    css: "@font-face { font-family: 'Ongle_ParkDaHyun'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2411-3@1.0/Ownglyph_ParkDaHyun.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'aggro',
    name: '어그로체',
    family: 'SBAggroB',
    css: "@font-face { font-family: 'SBAggroB'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2108@1.1/SBAggroB.woff') format('woff'); font-weight: 700; font-style: normal; }",
  },
  {
    id: 'atoz',
    name: '에이투지체',
    family: 'Atoz',
    css: "@font-face { font-family: 'Atoz'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2601-6@1.0/에이투지체-1Thin.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'cafe24-ssurround',
    name: '카페24 써라운드',
    family: 'Cafe24Ssurround',
    css: "@font-face { font-family: 'Cafe24Ssurround'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2105_2@1.0/Cafe24Ssurround.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'ok-dandan',
    name: 'Ok단단체',
    family: 'OkDandan',
    css: "@font-face { font-family: 'OkDandan'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2508-2@1.0/OkDanDan-Bold.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'jeju-doldam',
    name: '제주돌담체',
    family: 'JejuDoldam',
    css: "@font-face { font-family: 'JejuDoldam'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2210-EF@1.0/EF_jejudoldam.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'pyeongchang-peace',
    name: '평창평화체',
    family: 'PyeongChangPeace-Bold',
    css: "@font-face { font-family: 'PyeongChangPeace-Bold'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2206-02@1.0/PyeongChangPeace-Bold.woff2') format('woff2'); font-weight: 700; font-style: normal; }",
  },
  {
    id: 'lee-seoyun',
    name: '이서윤체',
    family: 'LeeSeoyun',
    css: "@font-face { font-family: 'LeeSeoyun'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2202-2@1.0/LeeSeoyun.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'maruminya',
    name: '마루미냐 한글',
    family: 'Maruminya',
    css: "@font-face { font-family: 'Maruminya'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2604-1@1.1/x12y12pxMaruMinyaHangul.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'elegant-serif',
    name: '우아한 세리프',
    family: 'ElegantSerif',
    css: "@font-face { font-family: 'ElegantSerif'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2604-1@1.0/GraceSerif-Regular.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'police-emotion',
    name: '그리운 경찰감성체',
    family: 'PoliceEmotion',
    css: "@font-face { font-family: 'PoliceEmotion'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2601-6@1.0/Griun_PolSensibility-Rg.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'jua',
    name: '주아체',
    family: 'BMJUA',
    css: "@font-face { font-family: 'BMJUA'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/BMJUA.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'keris-kedu',
    name: '케리스 케듀체',
    family: 'KerisKedu',
    css: "@font-face { font-family: 'KerisKedu'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2601-3@1.0/KERISKEDU_R.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'kkubullim',
    name: '꾸불림체',
    family: 'Kkubullim',
    css: "@font-face { font-family: 'Kkubullim'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2410-1@1.0/BMkkubulimTTF-Regular.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'ongle-positivity',
    name: '온글잎 긍정',
    family: 'Ongle_Positivity',
    css: "@font-face { font-family: 'Ongle_Positivity'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2604-1@1.1/Ownglyph_positive.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'ria',
    name: '리아체',
    family: 'Ria',
    css: "@font-face { font-family: 'Ria'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2410-1@1.0/RiaSans-ExtraBold.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'wild-gak',
    name: '와일드각',
    family: 'WildGak',
    css: "@font-face { font-family: 'WildGak'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2510-1@1.0/KIMWILDgag-Bold.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'kbl-jump-extended',
    name: 'KBL점프체 Extended',
    family: 'KBLJumpExtended',
    css: "@font-face { font-family: 'KBLJumpExtended'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2601-5@1.0/KBLJump_EB_ExtendedTTF.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'ongle-konkon',
    name: '온글잎 콘콘체',
    family: 'Ongle_Konkon',
    css: "@font-face { font-family: 'Ongle_Konkon'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2412-1@1.0/Ownglyph_corncorn-Rg.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'isamanru',
    name: '이사만루',
    family: 'Isamanru-Bold',
    css: "@font-face { font-family: 'Isamanru-Bold'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10@1.0/GongGothicLight.woff') format('woff'); font-weight: 700; font-style: normal; }",
  },
  {
    id: 'gangwon-edu-all',
    name: '강원교육 모두체',
    family: 'GangwonEduAll',
    css: "@font-face { font-family: 'GangwonEduAll'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2201-2@1.0/GangwonEdu_OTFLightA.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'jalnan-gothic',
    name: '여기어때 잘난체 고딕',
    family: 'JalnanGothic',
    css: "@font-face { font-family: 'JalnanGothic'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_231029@1.1/JalnanGothic.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'maplestory',
    name: '넥슨 메이플스토리',
    family: 'MapleStory',
    css: "@font-face { font-family: 'MapleStory'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.1/MaplestoryOTFLight.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'heir-of-light',
    name: '빛의 계승자체',
    family: 'HeirofLight-Regular',
    css: "@font-face { font-family: 'HeirofLight-Regular'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-07@1.0/HeirofLightRegular.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'schoolsafe-notices',
    name: '학교안심 알림장',
    family: 'SchoolSafeNotices',
    css: "@font-face { font-family: 'SchoolSafeNotices'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2408-5@1.0/HakgyoansimAllimjangTTF-R.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'ongle-uiyeon',
    name: '온글잎 의연체',
    family: 'Ongle_Uiyeon',
    css: "@font-face { font-family: 'Ongle_Uiyeon'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2105@1.1/Uiyeun.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'kyobo-2025-lee-yubin',
    name: '교보문고 손글씨 2025',
    family: 'Kyobo2025LeeYubin',
    css: "@font-face { font-family: 'Kyobo2025LeeYubin'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2604-1@1.1/KyoboHandwriting2025lyb.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'fixedsys',
    name: '둥근모꼴',
    family: 'Fixedsys',
    css: "@font-face { font-family: 'Fixedsys'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/DungGeunMo.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'nanum-square-neo',
    name: '나눔스퀘어 네오',
    family: 'NanumSquareNeo-Variable',
    css: "@font-face { font-family: 'NanumSquareNeo-Variable'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_11-01@1.0/NanumSquareNeo-Variable.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'seoul-notice',
    name: '서울알림체',
    family: 'SeoulNotice',
    css: "@font-face { font-family: 'SeoulNotice'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2505-1@1.0/SeoulAlrimTTF-Medium.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'noto-serif-kr',
    name: '본명조 (Source Han Serif)',
    family: 'NotoSerifKR',
    css: "@font-face { font-family: 'NotoSerifKR'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/NotoSerifKR.woff') format('woff'); font-weight: 400; font-style: normal; }",
  },
  {
    id: 'dohyeon',
    name: '도현체',
    family: 'BMDOHYEON',
    css: "@font-face { font-family: 'BMDOHYEON'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/BMDOHYEON.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'ink-lipquid',
    name: '잉크립퀴드체',
    family: 'InkLipquid',
    css: "@font-face { font-family: 'InkLipquid'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/InkLipquid.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'one-mobile-pop',
    name: '원스토어 모바일',
    family: 'ONEMobilePOP',
    css: "@font-face { font-family: 'ONEMobilePOP'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2105_2@1.0/ONE-Mobile-POP.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'schoolsafe-roundsmile',
    name: '학교안심 둥근미소',
    family: 'SchoolSafeRoundSmile',
    css: "@font-face { font-family: 'SchoolSafeRoundSmile'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2408-5@1.0/HakgyoansimDunggeunmisoTTF-R.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'lotteria-chwab',
    name: '롯데리아 촵땡겨체',
    family: 'LotteriaChwab',
    css: "@font-face { font-family: 'LotteriaChwab'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/LOTTERIACHAB.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'nanum-square-round',
    name: '나눔스퀘어라운드',
    family: 'NanumSquareRound',
    css: "@font-face { font-family: 'NanumSquareRound'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/NanumSquareRound.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'omu-dayeppeum',
    name: '오뮤 다예쁨체',
    family: 'OmuDayeppeum',
    css: "@font-face { font-family: 'OmuDayeppeum'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2304-01@1.0/omyu_pretty.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'shilla-culture',
    name: '신라 문화체',
    family: 'ShillaCulture',
    css: "@font-face { font-family: 'ShillaCulture'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2304-01@1.0/omyu_pretty.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'keris-kedu-line',
    name: '케리스 케듀체 line',
    family: 'KerisKeduLine',
    css: "@font-face { font-family: 'KerisKeduLine'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2601-3@1.0/KERISKEDU_Line.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'cookierun',
    name: '쿠키런',
    family: 'CookieRun-Regular',
    css: "@font-face { font-family: 'CookieRun-Regular'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/CookieRun-Regular.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'police-fair',
    name: '그리운 경찰공평체',
    family: 'PoliceFair',
    css: "@font-face { font-family: 'PoliceFair'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2601-6@1.0/Griun_PolFairness-Rg.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'tmon-monsori',
    name: '티몬체',
    family: 'TmonMonsori',
    css: "@font-face { font-family: 'TmonMonsori'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/TmonMonsori.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'ridi-batang',
    name: '리디바탕',
    family: 'RidiBatang',
    css: "@font-face { font-family: 'RidiBatang'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_twelve@1.0/RIDIBatang.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'yeongwol',
    name: '영월체',
    family: 'Yeongwol',
    css: "@font-face { font-family: 'Yeongwol'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2507-2@1.0/YeongwolTTF-Regular.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'gangwon-edu-strong',
    name: '강원교육튼튼체',
    family: 'GangwonEduStrong',
    css: "@font-face { font-family: 'GangwonEduStrong'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2201-2@1.0/GangwonEduPowerExtraBoldA.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'the-jamsil',
    name: '더잠실체',
    family: 'TheJamsil',
    css: "@font-face { font-family: 'TheJamsil'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302_01@1.0/TheJamsil2Light.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'victory-day',
    name: '승리의 그날까지',
    family: 'VictoryDay',
    css: "@font-face { font-family: 'VictoryDay'; src: url('https://cdn.jsdelivr.net/gh/tillvictorycomes/TillVictoryComes-font/tillvictorycomes-Regular.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'nexon-lv1-gothic',
    name: '넥슨 Lv.1 고딕',
    family: 'NEXONLv1GothicOTF',
    css: "@font-face { font-family: 'NEXONLv1GothicOTF'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.1/NEXON Lv1 Gothic OTF.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'partial-sans',
    name: '파셜산스',
    family: 'PartialSans',
    css: "@font-face { font-family: 'PartialSans'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2307-1@1.1/PartialSansKR-Regular.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'gyeonggi-title',
    name: '경기천년제목',
    family: 'GyeonggiTitle',
    css: "@font-face { font-family: 'GyeonggiTitle'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2410-3@1.0/Title_Light.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'yangjin',
    name: '양진체',
    family: 'Yangjin',
    css: "@font-face { font-family: 'Yangjin'; src: url('https://cdn.jsdelivr.net/gh/supernovice-lab/font@0.9/yangjin.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'meetme',
    name: '밑미 폰트',
    family: 'MeetMe',
    css: "@font-face { font-family: 'MeetMe'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2402_1@1.0/Ownglyph_meetme-Rg.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'romantic-gumi',
    name: '낭만있구미체',
    family: 'RomanticGumi',
    css: "@font-face { font-family: 'RomanticGumi'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2410-1@1.0/GumiRomanceTTF.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'zen-serif',
    name: 'zenserif',
    family: 'ZenSerif',
    css: "@font-face { font-family: 'ZenSerif'; src: url('https://cdn.noonnu.cc/fonts/ZEN-SERIF-TTF-Regular.ttf') format('truetype'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'independence',
    name: '독립체',
    family: 'Independence',
    css: "@font-face { font-family: 'Independence'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_twelve@1.1/Dokrip.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'slow-gothic',
    name: '느림보고딕',
    family: 'SlowGothic',
    css: "@font-face { font-family: 'SlowGothic'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2304-01@1.0/neurimboGothicRegular.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'binggrae',
    name: '빙그레체',
    family: 'Binggrae',
    css: "@font-face { font-family: 'Binggrae'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/Binggrae.woff') format('woff'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'hs-santtokki-2',
    name: 'HS산토끼체 2.0',
    family: 'HSSanttokki-2.0',
    css: "@font-face { font-family: 'HSSanttokki-2.0'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2405@1.0/HSSanTokki20-Regular.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'laundry-gothic',
    name: '런드리고딕',
    family: 'LaundryGothic',
    css: "@font-face { font-family: 'LaundryGothic'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/2403-2@1.0/TTLaundryGothicR.woff2') format('woff2'); font-weight: normal; font-style: normal; }",
  },
  {
    id: 'changwon-dangam-asak',
    name: '창원단감아삭체',
    family: 'ChangwonDangamAsak',
    css: "@font-face { font-family: 'ChangwonDangamAsak'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2108@1.1/CWDangamAsac-Bold.woff') format('woff'); font-weight: normal; font-style: normal; }",
  }
];
